# Generated by Django 2.2.5 on 2021-08-22 11:12

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210822_2006'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
