# Generated by Django 2.2.5 on 2021-03-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20210217_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenitise',
            new_name='amenities',
        ),
    ]
