# Generated by Django 2.2.5 on 2021-08-27 11:07

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20210811_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='room_photos'),
        ),
    ]
